language: node_js
node_js:
  - '12.14.1'
script:
  - echo 'Deploying!' && npm install && npm run build
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --token $FIREBASE_TOKEN
  # "firebase login:ci" commend to generate FIREBASE_TOKEN
branches:
  only:
    - master
